default_platform(:android)

platform :android do
  desc "Build App for development"
  lane :build do
    gradle(task: "assembleDebug")
  end

  desc "Build App for release"
  lane :release do
    gradle(task: "assembleRelease")
  end

  desc "Upload App to Play store"
  lane :production do
    upload_to_play_store(
      track: 'production',
      apk: 'app/build/outputs/apk/release/app-release.apk'
    )
  end
end